sudo: required

language: php

php: [7.0, 7.1]

before_install:
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get update -q
  - sudo apt-get install libsodium-dev -y

install:
  - travis_retry pecl install libsodium
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - mkdir -p build/logs
  - php bin/phpcs --standard=PSR2 ./src/ --report=full --ignore=compatibility.php,functions.php
  - php bin/phpspec run --format=pretty -v

after_success:
  - travis_retry php bin/coveralls -v

cache:
    directories:
        - $HOME/.composer/cache

